apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel-operator-system
resources:
- ../dev
patches: []
secretGenerator:
- name: cloudflare-tunnel-operator-secret-dev
  behavior: replace
  envs:
  - .env # actual secret file (not commit)
