apiVersion: cloudflare-tunnel.pollenjp.com/v1alpha1
kind: CloudflareTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-tunnel-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-sample
spec:
  # TODO(user): Add fields here
  # cloudflared_config.yaml: |
  #   # metrics: <metrics-endpoint>
  #   # no-autoupdate: <no-autoupdate>
